// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC61x2iOA2BXJRcEcQymWJySa0ajXAlTno',
    appId: '1:206192120187:web:a6d0cffdab614165766dde',
    messagingSenderId: '206192120187',
    projectId: 'shesafe-test',
    authDomain: 'shesafe-test.firebaseapp.com',
    storageBucket: 'shesafe-test.appspot.com',
    measurementId: 'G-KYK60CTH21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAQUF_badO45Ej77oEbvtXfUGTL-_wOY',
    appId: '1:206192120187:android:f8c8d557639000ed766dde',
    messagingSenderId: '206192120187',
    projectId: 'shesafe-test',
    storageBucket: 'shesafe-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi2YUbSryZr6LOCqstPmJ9iXoCSW9nWkc',
    appId: '1:206192120187:ios:55dded21f29277cc766dde',
    messagingSenderId: '206192120187',
    projectId: 'shesafe-test',
    storageBucket: 'shesafe-test.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi2YUbSryZr6LOCqstPmJ9iXoCSW9nWkc',
    appId: '1:206192120187:ios:b3627aeea88ea61c766dde',
    messagingSenderId: '206192120187',
    projectId: 'shesafe-test',
    storageBucket: 'shesafe-test.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
